name: Boilerplate CI

on:
  push:
    branches: [staging]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate .env
        run: |
          envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./environments/staging.env > ./environments/$NODE_ENV.env
          echo "$(cat ./environments/$NODE_ENV.env)"

          envsubst < docker-compose.template.yml > docker-compose.yml
          echo "$(cat ./docker-compose.yml)"
        env:
          PORT: 4020
          APP_ENV: staging
          NODE_ENV: staging

          S3_ENDPOINT:
          S3_ACCESS_KEY:
          S3_SECRET_KEY:
          S3_BUCKET:

          #
          # Redis
          #
          REDIS_HOST:
          REDIS_PORT:
          REDIS_PASSWORD:

          #
          # Infra
          #
          DOCKER_SERVICE_NAME: lms-staging

      - name: Log in to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/lms-staging:latest

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/lms-staging:latest

      - name: Ensure Docker Compose, Env File Exist
        run: |
          if [ ! -f environments/staging.env ]; then
            echo "File environments/staging.env does not exist."
            exit 1
          fi
          if [ ! -f docker-compose.yml ]; then
            echo "File docker-compose.yml does not exist."
            exit 1
          fi

      - name: Transfer Docker Compose, Env File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'environments,docker-compose.yml'
          target: '~/deploy/lms-staging'

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deploy/lms-staging

            echo "Logging to Docker Hub"
            docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

            echo "Stopping previous build"
            docker stop lms-staging || true

            echo "Removing previous build"
            docker rm lms-staging || true

            echo "Remove previous image"
            docker image prune -a -f

            echo "Starting latest build"
            docker compose --env-file environments/staging.env -f docker-compose.yml up -d

            echo "Deploy Done"
